name: expense_manager
description: A new Flutter application.

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  theme_provider: ^0.4.0+1
  animations: ^1.1.2
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  toast: ^0.1.5
  syncfusion_flutter_charts: ^18.4.44+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.10

flutter:
  uses-material-design: true
  assets:
    - assets/meme.jpg
    - assets/work_in_progress.png
