name: expense_manager
description: A new Flutter application.

publish_to: 'none'

version: 0.0.3+3

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  theme_provider: any
  animations: any
  hive: any
  hive_flutter: any
  path_provider: any
  toast: any
  syncfusion_flutter_charts: any

#  cupertino_icons: ^0.1.3
#  theme_provider: ^0.4.0+1
#  animations: ^1.1.2
#  hive: ^1.4.4+1
#  hive_flutter: ^0.3.1
#  path_provider: ^1.6.24
#  toast: ^0.1.5
#  syncfusion_flutter_charts: ^18.4.44+1

dependency_overrides:
  # Override path_provider to pick up fixes for FFI changes.
  path_provider: ^2.0.0-nullsafety.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.10

flutter:
  uses-material-design: true
  #assets:


